export const ECONOMY = {
  // GDP
  GDP_MOMENTUM: 0.90,

  // Component adjustment speeds
  CONSUMPTION_ADJUSTMENT: 0.12,
  INVESTMENT_ADJUSTMENT: 0.12,

  // Inflation
  INFLATION_ADJUSTMENT: 0.20,
  NEUTRAL_INTEREST_RATE: 2.5,

  // Labor market
  UNEMPLOYMENT_ADJUSTMENT: 0.35,
  NEUTRAL_LABOR_RATE: 3.0,

  // Long-run growth
  BASE_PRODUCTIVITY_GROWTH: 0.001,
  EDUCATION_PRODUCTIVITY_MULTIPLIER: 0.000002,
  SCIENCE_PRODUCTIVITY_MULTIPLIER: 0.000003,
  INFRASTRUCTURE_POTENTIAL_GDP_MULTIPLIER: 0.000002,

  // Treasury
  TAXABLE_SHARE_OF_GDP: 0.65,

  // Simulation limits
  MIN_INFLATION: -2,
  MAX_INFLATION: 15,

  MIN_UNEMPLOYMENT: 2,
  MAX_UNEMPLOYMENT: 25,
} as const;